#!/bin/bash

set -euo pipefail

swift --version

swift package \
    dollup --allow-writing-to-package-directory
swift package --package-path Examples \
    dollup --allow-writing-to-package-directory

git diff --exit-code
